data:
  train_dataset:
    - data/train/guychuk_data5000.csv
    - data/train/harelix_dataset.csv
    - data/train/GPT_generated_dataset.csv
    - data/train/deepset_train.csv

  test_dataset:
    - data/test/promptshield_dataset.csv
    - data/test/jackhhao_jailbreak_dataset.csv
    - data/test/curated_test.csv
    - data/test/qualifire.csv

language_model:
  llama: "meta-llama/Llama-3.2-1B"
  qwen: "Qwen/Qwen2.5-1.5B-Instruct"
  phi: "microsoft/Phi-3-mini-128k-instruct"