data:
  train_dataset:
    - data/1-raw/train/guychuk_data5000.csv
    - data/1-raw/train/harelix_dataset.csv
    - data/1-raw/train/GPT_generated_dataset.csv
    - data/1-raw/train/deepset_train.csv

  test_dataset:
    - data/1-raw/test/promptshield_dataset.csv
    - data/1-raw/test/jackhhao_jailbreak_dataset.csv
    - data/1-raw/test/curated_test.csv
    - data/1-raw/test/qualifire_test.csv

  train_features: "data/2-features/qwen_trainset_features.csv"
  test_features: "data/2-features/??"

language_model:
  llama: "meta-llama/Llama-3.2-1B"
  qwen: "Qwen/Qwen2.5-1.5B-Instruct"
  phi: "microsoft/Phi-3-mini-128k-instruct"

language_model_parameters:
  output_attentions: True
  return_dict_in_generate: True
  attn_implementation: "eager"
  device_map: "auto"